#!/bin/sh

composer test
appver=$(grep -o -E '\d.\d.\d' cghooks)
tag=$(git describe --tags --abbrev=0)
if [ "$tag" != "v$appver" ]; then
echo "The most recent tag $tag does not match the application version $appver\n"
tag=${tag#v}
sed -i -E "s/$appver/$tag/" cghooks
exit 1
fi
